name: Main workflow

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * 5"

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all tags
        run: git fetch --depth 1 origin +refs/tags/*:refs/tags/*

      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install coreutils # needed by bats-core
          brew install fish # for testing asdf.fish

      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          PPA="ppa:fish-shell/nightly-master"
          sudo add-apt-repository -y "$PPA"
          sudo apt-get update
          sudo apt-get -y install fish

      - name: Install bats-core on Windows
        if: matrix.os == 'windows-latest'
        run: npm install -g bats@1.1.0

      - name: Install bats-core on Unix systems
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: |
          git clone --depth 1 --branch v1.1.0 https://github.com/bats-core/bats-core.git $HOME/bats-core
          echo "::add-path::$HOME/bats-core/bin"

      - name: Run tests on Windows
        if: matrix.os == 'windows-latest'
        run: bats test
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Run tests on Unix systems
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: bats test
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install shellcheck
        run: sudo apt-get install shellcheck

      - name: Run ShellCheck
        run: bash lint.sh

  format:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install shfmt
        run: brew install shfmt

      - name: List file to shfmt
        run: shfmt -f .

      - name: Run shfmt
        run: shfmt -d .
